#!/bin/sh

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

alias \
  fdate="date '+%Y %b %d (%a) %I:%M%p'" \
  cp="cp -iv" \
  mv="mv -iv" \
  rm="rm -vI" \
  mkd="mkdir -pv" \
  yt="youtube-dl --add-metadata -i" \
  yta="yt -x -f bestaudio/best" \
  ffmpeg="ffmpeg -hide_banner" \
  grep="grep --color=auto" \
  diff="diff --color=auto" \
  ccat="highlight --out-format=ansi" \
  sdn="sudo shutdown -h now" \
  p="sudo pacman" \
  ps="pacman -Slq | fzf --multi --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S" \
  ys="yay -Slq | fzf --multi --preview 'yay -Si {1}' | xargs -ro yay --removemake --cleanafter --nodiffmenu -S" \
  mnt="sudo mount" \
  umnt="sudo umount" \
  smake="sudo make clean install" \
  ls="ls -A" \
  ll="ls -AlhN --color=auto --sort=extension" \
  ls="ls --color=auto" \
  rsync="rsync --progress" \
  tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \
  gp="git remote | xargs -L1 git push --all" \
  gs="git status -s" \
  gl="git log" \
  gm="git add . && git commit -m" \
  gam="git commit -a -m"
