#!/bin/bash

# Check whether the external monitor is connected
#xrandr | grep -Ev "eDP1" | grep " connected "

#if [ $? -eq 0 ]; then
#  CON_DISPLAY="$(xrandr | grep -Ev "eDP1" | grep " connected " | cut -d " " -f1)"
#  xrandr --output "$CON_DISPLAY" --mode 2560x1080 --rate 75 --primary
#  xrandr --output eDP1 --mode 1920x1080 --rate 60 --right-of "$CON_DISPLAY"
#fi

xrandr --output eDP1 --auto 
xrandr --output DP1-2 --mode 2560x1080 --rate 75 --left-of eDP1
xrandr --output DP1-3 --auto --right-of eDP1

source "$HOME"/.fehbg

#mpd &
xcompmgr &
dunst &
xset r rate 300 50 &
