#!/bin/sh
mpd &
xrandr --output DP-1 --primary --mode 1920x1080 --pos 468x1050 --rotate normal \
       --output DP-2 --mode 1680x1050 --pos 0x0 --rotate inverted \
       --output DP-3 --off \
       --output HDMI-1 --mode 1680x1050 --pos 1680x0 --rotate inverted
[[ -f "$WALLPAPERS/background" ]] && feh --bg-scale "$WALLPAPERS/background" || setbg
xcompmgr &
dunst &
xset r rate 300 50 &
