#!/bin/sh
sh $HOME/.config/screenlayout/desktop-pc.sh # Load screenlayout script (you WONT need this)
xset r rate 300 50 & # Increase xrate (trust me, you want this)
setbg & # Load a random wallpaper from ~/data/pix
xcompmgr & # Load comp manager for transparency
/usr/bin/setxkbmap -option "caps:swapescape" # Switch ESC and CAPS (who uses CAPS??)
